apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2024-10-02T03:12:17Z"
  labels:
    run: my-nginx
  name: my-nginx
  namespace: default
  resourceVersion: "5145"
  uid: 533e496e-a6d3-4e8e-a43a-7aee4c2bf514
spec:
  containers:
  - image: nginx:latest
    imagePullPolicy: IfNotPresent
    name: my-nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-thc46
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: cluster-66e67aa3b346c925a31c0b9f-cda-worker-1
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: kube-api-access-thc46
    projected:
      defaultMode: 420
      sources:
      - serviceAccountToken:
          expirationSeconds: 3607
          path: token
      - configMap:
          items:
          - key: ca.crt
            path: ca.crt
          name: kube-root-ca.crt
      - downwardAPI:
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
            path: namespace
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T03:12:27Z"
    status: "True"
    type: PodReadyToStartContainers
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T03:12:17Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T03:12:27Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T03:12:27Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2024-10-02T03:12:17Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: containerd://981069b651f0856a9d53556bcfdca77292c54b8ee7000b027474784122c963d9
    image: docker.io/library/nginx:1.26
    imageID: docker.io/library/nginx@sha256:42a11c50654d46498c9f0f1108e95cd82776a98e2b8632a3c1839dcd3ac23e0e
    lastState: {}
    name: my-nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2024-10-02T03:12:26Z"
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: kube-api-access-thc46
      readOnly: true
      recursiveReadOnly: Disabled
  hostIP: 10.62.2.30
  hostIPs:
  - ip: 10.62.2.30
  phase: Running
  podIP: 10.42.2.3
  podIPs:
  - ip: 10.42.2.3
  qosClass: BestEffort
  startTime: "2024-10-02T03:12:17Z"
